site_name: Phoenix
site_url: https://your.docs.url
repo_url: https://github.com/Arize-ai/phoenix
docs_dir: api_docs

theme:
  name: material
  features:
    - navigation.sections
    - navigation.tracking
    - navigation.tabs
    - navigation.instant
    - toc.follow
    - content.code.copy
    - content.action.edit
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
extra_css:
  - styles/nav-hierarchy.css

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      default_lang: python
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist

plugins:
  - search
  - gen-files:
      scripts:
        - api_docs/generate.py
  - section-index
  - literate-nav
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          options:
            docstring_style: google
            docstring_section_style: table
            # Don't set members globally - let individual directives control it
            inherited_members: false
            group_by_category: true
            show_category_heading: true
            show_root_heading: true
            heading_level: 2
            show_signature: false
            separate_signature: false
            show_signature_annotations: false
            show_if_no_docstring: false
            members_order: source
            filters:
              - "!^_"  # Exclude all private members
            merge_init_into_class: true
            line_length: 100

nav:
  - Overview: index.md
  - Guides: guides/index.md
  - Phoenix OTEL: api/phoenix-otel/phoenix.otel.md
  - Phoenix Client: api/phoenix-client/index.md
  - Phoenix Evals: api/phoenix-evals/index.md
  - Phoenix: api/phoenix/index.md
