apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: phoenix
spec:
  template:
    spec:
      containers:
      - name: phoenix
        env:
        - name: PHOENIX_ENABLE_AUTH
          value: "true"
        - name: PHOENIX_SECRET
          valueFrom:
            secretKeyRef:
              name: phoenix-secret
              key: PHOENIX_SECRET
