name: Sync Model Pricing Data

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - xander/cost-sync

jobs:
  sync-model-pricing:
    name: Sync Model Pricing Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/setup-python@v5
      
      - uses: astral-sh/setup-uv@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run LiteLLM sync script
        id: sync-litellm
        run: python scripts/sync_litellm_models.py
      
      - name: Check for changes
        id: verify-changed-files
        run: |
          if git diff --exit-code src/phoenix/server/cost_tracking/model_cost_manifest.json; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            ADDED=$(git diff src/phoenix/server/cost_tracking/model_cost_manifest.json | grep -c '^+' || true)
            REMOVED=$(git diff src/phoenix/server/cost_tracking/model_cost_manifest.json | grep -c '^-' || true)
            echo "lines_added=$ADDED" >> $GITHUB_OUTPUT
            echo "lines_removed=$REMOVED" >> $GITHUB_OUTPUT
          fi
      
      - name: Create Pull Request
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update built-in model token prices (${{ steps.sync-litellm.outputs.timestamp }})"
          title: "chore: update built-in model token prices (${{ steps.sync-litellm.outputs.timestamp }})"
          body: |
            This change was automatically generated by the sync-model-pricing workflow.
          branch: update-model-pricing-${{ steps.sync-litellm.outputs.timestamp }}
          base: xander/cost-sync
          delete-branch: true
