name: Playwright Tests

env:
  pip-version: 24.2

on:
  push:
    branches: [auth, main]
  pull_request:
    branches: [auth, main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        working-directory: ./app
        run: npm install -g pnpm && pnpm install
      - name: Install Playwright Browsers
        working-directory: ./app
        run: pnpm exec playwright install --with-deps
      - name: Build the app
        working-directory: ./app
        run: pnpm run build
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - uses: yezz123/setup-uv@v4
        with:
          uv-version: 0.4.8
      - run: uv pip install .
      - name: Run Playwright tests
        working-directory: ./app
        run: pnpm exec playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: app/playwright-report/
          retention-days: 30
